CREATE TABLE PRODUCTS
(
    NAME VARCHAR2(4000) PRIMARY KEY NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    PRICE INTEGER NOT NULL,
    IMAGE VARCHAR2(4000),
    STOCK INTEGER NOT NULL,
    CATEGORY VARCHAR2(20) NOT NULL
);

INSERT INTO HR.PRODUCTS (NAME, DESCRIPTION, PRICE, IMAGE, STOCK, CATEGORY) VALUES ('Onions', 'Rich in vitamins', 55, 'img/onions.jpg', 230, 'vegetables');
INSERT INTO HR.PRODUCTS (NAME, DESCRIPTION, PRICE, IMAGE, STOCK, CATEGORY) VALUES ('Tomatoes', 'Rich in Iron', 34, 'img/tomatoes.jpg', 180, 'fruit');

