CREATE TABLE USERS
(
  USERNAME VARCHAR2(4000) PRIMARY KEY NOT NULL,
  PASSWORD VARCHAR2(4000) NOT NULL,
  VCODE INTEGER,
  VERIFIED INTEGER,
  USER_TYPE INTEGER
);
INSERT INTO HR.USERS (USERNAME, PASSWORD, VCODE, VERIFIED, USER_TYPE) VALUES ('f.warren210@gmail.com', 'lol', 1209194976, 1, 1);
